version: '2.2'

volumes:
  nginx-data:
  nginx-logs: 
  resin-data2:

services:
  nginx:
    build: ./nginx
    container_name: container-nginx
    networks:
      - default
    ports:
      - 80:80
    restart: always

  api:
    build: ./moedas/api
    container_name: container-api
    networks: 
      - default
    ports:
      - 8001:8001
    depends_on:
      - db
    environment:
      - DB_HOST=db
    command: ["python3", "manage.py", "runserver", "0.0.0.0:80"]

  db:
    image: postgres:alpine3.18
    container_name: container-db
    networks: 
      - default
    restart: always
    volumes:
      - 'resin-data2:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: container-pgadmin
    networks: 
      - default
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - db

networks:
  default:
    external:
      name: network-nginx
