version: '2.2'

volumes:
  nginx-data:
  nginx-logs: 
  postgres-data:

services:
  nginx:
    build: ./nginx
    container_name: container-nginx
    networks:
      - default
    ports:
      - 80:80
    restart: always

  api:
    build: ./moedas/api
    container_name: container-api
    networks: 
      - default
    ports:
      - 8001:8001

  db:
    image: postgres:alpine3.18
    container_name: container-db
    networks: 
      - default
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "5432" 

networks:
  default:
    external:
      name: network-nginx
