version: '2.1'

volumes:
  nginx-data:
  nginx-logs:

services:
  nginx:
    build: ./nginx
    container_name: container-nginx
    ports:
      - 80:80
    restart: always
    networks:
      - default

  api:
    build: ./api
    container_name: container-api
    networks: 
      - default

  db:
    build: ./db
    container_name: container-db
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks: 
      - default

networks:
  default:
    external:
      name: nginx-proxy

