worker_processes 4;

events { worker_connections 1024; }

http {    
    client_max_body_size 50M;

    server {
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/letsencrypt/live/api.pharus.website/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.pharus.website/privkey.pem;
        ssl_prefer_server_ciphers off;

        server_name api.pharus.website www.api.pharus.website;
        

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            proxy_set_header  X-Script-Name /api;
            proxy_set_header Host $host;
            proxy_pass http://api/api/;
        }

        location /pgadmin/ {
            proxy_set_header X-Script-Name /pgadmin;
            proxy_set_header Host $host;
            proxy_pass http://pgadmin:5050/;
            proxy_redirect off;
        }
    }
}
